### ISSUE TITLE
query regarding the meshsegnet baseline

### ISSUE THREAD

**Issue by ananyajana** [Tai-Hsien/PointNet_Seg#2]
Hi @Tai-Hsien - did you use the code present in this repo for the pointnet baseline in MeshSegNet?

**Comment by Tai-Hsien** [comment]
Hello @ananyajana 
The results reported in MeshSegNet paper were conducted from my colleagues. They didn't use this repo directly, but the concept of codes are the same.

**Comment by ananyajana** [comment]
Thank you @Tai-Hsien.
